name: Deploy to Cloudflare Pages
on:
 push:
   branches:
     - master
jobs :
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
         dotnet-version: '8.0.x'
        
      - name: Publish Blazor WebAssembly
        run: dotnet publish -c Release -o publish
        
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: pages deploy publish/wwwroot -- project-name=blazortestapp
